### ISSUE TITLE
Ajout de la configuration maven pour l'exécution des classes Main

### ISSUE THREAD

**Issue by alexandre-touret** [jmdoudoux/workshop-javase-2024#2]
Pour permettre d'exécuter les classes main avec maven, il pourrait être intéressant d'ajouter dans le workshop les éléments suivants:

Documentation

Ajout chapitre 3.2.4 de la ligne de commande suivante:

```bash
mvn compile exec:java -Dexec.mainClass="fr.sciam.workshop.javase.records.MainRecord"
``` 

Dans le repo, pour permettre l'exécution des classes qui utilisent des features preview, il est nécessaire de créer le fichier ``.mvn/jvm.config`` avec le contenu suivant:

```
--enable-preview
```

**Comment by CodeSimcoe** [comment]
Corrigé, sera dispo dans la prochaine mouture !
