### ISSUE TITLE
Précision à ajouter dans le lab 5.3.1 formatage des nombres compacts

### ISSUE THREAD

**Issue by alexandre-touret** [jmdoudoux/workshop-javase-2024#4]
Bonjour,
l'affichage de la méthode ``parser()`` 

```java
private static void parser() {
    try {
      List<String> elements = ListFormat.getInstance()
          .parse("Ni, Cu, Zn et Fe");
      System.out.println(elements);
    } catch (ParseException e) {
      e.printStackTrace(System.out);
    }
  }

```

ne fonctione dans le cas mentionné dans le tp seulement si la locale de l'environnement est FR.

Dans le cas d'un PC anglais avec la variable LANG à ``C.UTF-8`` , le "et" n'est pas interprété.

**Comment by CodeSimcoe** [comment]
Corrigé, sera dispo dans la prochaine mouture !
